### PR TITLE
Avoid requiring SA in Flux plugin in the UI

### LINKED ISSUE #5522: Deploy package form: service account selection should be optional
Filing  bug per @antgamdia request. When installing a flux package I am forced to select a service account in the dashboard ? service account name is [optional](https://fluxcd.io/flux/components/helm/helmreleases/) on the backend, why is the UI forcing me to pick one?
Screen Shot 2022-10-20 at 12 43 19 AM

### PR DESCRIPTION
**Pull request by antgamdia**
### Description of the change

This PR removed the `required=true` UI validation if using the Flux plugin for installing a package.

### Benefits

UI consistent with the Flux backend.

### Possible drawbacks

N/A

### Applicable issues

- fixes #5522

### Additional information

image

### CODE REVIEW

**Comment by absoludity** [comment]
See comment on the issue at https://github.com/vmware-tanzu/kubeapps/issues/5522#issuecomment-1286234267

**Review by castelblanque — APPROVED** [review]
LGTM

**Comment by antgamdia** [comment]
Interestingly, e2e tests are consistently failing. It seems the expected dropdown option can't be found. Will have a look at it:

````
    waiting for selector "#serviceaccount-selector select"
      selector resolved to visible <select slot="input" id="_xt3jpg5jx" aria-describedby="_…>…</select>
      selecting specified option(s)
        did not find some options - waiting... 
    ============================================================

      34 |   const releaseName = utils.getRandomName("test-04-release");
      35 |   await releaseNameLocator.fill(releaseName);
    > 36 |   await page.selectOption("#serviceaccount-selector select", "flux-reconciler");
         |              ^
      37 |   await page.locator('cds-button:has-text("Deploy")').click();
      38 |   console.log(`Creating release "${releaseName}"`);
````

**Comment by ppbaena** [comment]
It's great our CI help us to identify this kind of issues.

**Pull request merged**
