### PR TITLE
Run flux e2e test group in GHA's local_e2e_tests job

### PR DESCRIPTION
**Pull request by beni0888**
Signed-off-by: Jesús Benito Calzada <bjesus@vmware.com>

### Description of the change

It seems that at some point, a new `flux` test group has been added to the `/script/e2e_test.sh` file, but we have forgotten to add it to the GHA's `local_e2e_tests` job, so this test group is not being run in the GHA workflow. 

I have also took advantage of this PR to simplify the `local_e2e_tests` GHA job by setting a timeout of 6 minutes for every tests group, instead of having a default of 4 and setting it to 6 for the operator's group to avoid flaky tests.

### Benefits

* Run all the e2e tests from GHA.

### Possible drawbacks

N/A

### Applicable issues

- related to #4436

### CODE REVIEW

**Review by antgamdia — APPROVED** [review]
Let's see if this fixes the error. However, I don't know why it started failing out of the blue :S

**Review by absoludity — APPROVED** [review]
I'll re-run the e2e test, looks like it failed this time while installing the source controller...

```
Waiting for deployment "helm-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "helm-controller" successfully rolled out
+ kubectl rollout status -w deployment/source-controller --namespace=flux-system
Waiting for deployment "source-controller" rollout to finish: 0 of 1 updated replicas are available...
error: deployment "source-controller" exceeded its progress deadline
Error: Process completed with exit code 1.
```

**Comment by gfichtenholt** [comment]
> I'll re-run the e2e test, looks like it failed this time while installing the source controller...
> 
> ```
> Waiting for deployment "helm-controller" rollout to finish: 0 of 1 updated replicas are available...
> deployment "helm-controller" successfully rolled out
> + kubectl rollout status -w deployment/source-controller --namespace=flux-system
> Waiting for deployment "source-controller" rollout to finish: 0 of 1 updated replicas are available...
> error: deployment "source-controller" exceeded its progress deadline
> Error: Process completed with exit code 1.
> ```
> 
> EDIT: appears to be failing consistently at that point :/

No idea why this would happen. Maybe we should have retries with `kubectl rollout `and/or `describe deployment `if it fails, kind of like libtest.sh is doing?

**Comment by gfichtenholt** [comment]
closing because merged PR https://github.com/vmware-tanzu/kubeapps/pull/5656 has these changes

**Pull request closed without merging**
