### PR TITLE
Clean and tidy up the `pkg/` dir

### PR DESCRIPTION
**Pull request by antgamdia**
### Description of the change

Having removed the `assetsvc` makes possible to clean up the `pkg/*` directory, moving those no longer "common" dependencies to the proper module or even deleting unused code.

### Benefits

Less unused and/or misplaced code.

### Possible drawbacks

The changes mainly consist of moving and deleting code... but who knows if my IDE search function wasn't working properly.... let's our CI decide :P

### Applicable issues

- related #4847

### Additional information

See a post-PR analysis in my comment: https://github.com/vmware-tanzu/kubeapps/issues/4847#issuecomment-1150520731

### CODE REVIEW

**Review by absoludity — APPROVED** [review]
Odd that git didn't pick up some of the moved files (instead sees them as deleted and added).

**Comment by castelblanque** [comment]
Great work Antonio!
Just one question: why still using `cmd/kubeops` path name if we will get rid of it?

> Odd that git didn't pick up some of the moved files (instead sees them as deleted and added).

For Git, a file is identified not only by the name, but by the content (hashed). Content in files seems to be modified too, so for Git is a different file.

**Comment by antgamdia** [comment]
> Just one question: why still using cmd/kubeops path name if we will get rid of it?

Currently, `kubeops` is a necessary service as it is running the -current- API for repositories, as well as performing some requests to k8s (which should be migrated to the Resources plugin). There is an open issue for that: #4785 
This removal, consequently, is still assuming `kubeops` is still there but, yep, another removal like this one ought to be performed once we start sunsetting kubeops.

**Comment by absoludity** [comment]
> > Odd that git didn't pick up some of the moved files (instead sees them as deleted and added).
> 
> For Git, a file is identified not only by the name, but by the content (hashed). Content in files seems to be modified too, so for Git is a different file.

I'm pretty sure Git does more than just compare the hash to see if an added and removed file match - it applies some other heuristics which are usually pretty good at determining moved files. But if there are a lot of moved files with lots of changes in the files (more than 50%) the heuristic is less successful, from what I understand. See https://vjeko.com/2020/11/24/understanding-renaming-moving-files-with-git/ for some examples. Interestingly, their recommendation of renaming/content change in different commits doesn't work when we squash commits (because the separate commits won't exist in the main branch).

**Pull request merged**
