### PR TITLE
logs if helm repo empty instead throws error

### LINKED ISSUE #4611: helm repo with empty index throws error
### Description:

An empty `helm` chart repo is queried by the `apprepo-kubeapps-sync` job which then errors. I believe it should just report "No charts found."

### Steps to reproduce the issue:

1. add a chart repo with no charts in it
2. observe job erroring: `apprepo-kubeapps-sync-$name-...`

### PR DESCRIPTION
**Pull request by hzliangbin**
### Description of the change
just print logs if helm repo empty instead throws error

### Benefits
sync job will come to a Compelte state instead of error, it's more user-friendly

### Applicable issues

- fixes #4611

### CODE REVIEW

**Review by absoludity — APPROVED** [review]
Excellent, thanks for jumping in to fix it @hzliangbin .

**Review by absoludity — CHANGES_REQUESTED** [review]
Sorry @hzliangbin , could you please add the DCO sign-off to your commit? Instructions for how to do this are at https://github.com/vmware-tanzu/kubeapps/blob/main/CONTRIBUTING.md#dco-sign-off

Thanks!

**Comment by hzliangbin** [comment]
@absoludity PTAL

**Review by absoludity — APPROVED** [review]
Excellent, thanks @hzliangbin :)

**Pull request merged**
