### PR TITLE
Add golangci-lint gh action

### PR DESCRIPTION
**Pull request by antgamdia**
### Description of the change

This PR just adds `golangci-lint` as a github action. We were thinking of adding this linter in building time, but perhaps the GitHub action could be also an interesting option (it adds the checks directly as annotations, so perhaps it's better, not sure yet).

### Benefits

Our go code will pass the linters before being merged.

### Possible drawbacks

N/A

### Applicable issues

- fixes https://github.com/vmware-tanzu/kubeapps/issues/3087
- fixes https://github.com/vmware-tanzu/kubeapps/issues/2750

### Additional information
 
N/A

### CODE REVIEW

**Comment by antgamdia** [comment]
This PR is not displaying the "visual" checks because there is already failing code and, also, the PR is not adding any golang code.
It should show something like:

image

Marking as a draft while we start fixing the existing issues.

**Comment by castelblanque** [comment]
This is a great help. We are going to get rid of a lot of unused stuff, while keeping our source code "in shape" 😄

**Comment by antgamdia** [comment]
(Note that this PR should pass once https://github.com/vmware-tanzu/kubeapps/pull/5060, https://github.com/vmware-tanzu/kubeapps/pull/5059 and https://github.com/vmware-tanzu/kubeapps/pull/5058 get merged into this branch)

**Comment by antgamdia** [comment]
Tests finally passing :)

**Pull request merged**
