### PR TITLE
Issue4870 - removed use of UserManagedSecrets flag for helm plugin repos

### PR DESCRIPTION
**Pull request by dlaloue-vmware**
refactored helm plugin to not depend on a system flag "UserManagedSecrets" but allow secrets to be managed by user or by kubeapps per repository (issue #4870)

### CODE REVIEW

**Review by castelblanque — APPROVED** [review]
LGTM. Please change the title to a more descriptive one, for future reference.
Also add reference to the actual issue number that this PR is implementing/fixing, please.
Thanks.

**Comment by ppbaena** [comment]
Agree with Rafa about the PR title and reference to the issue.

**Review by antgamdia — APPROVED** [review]
Awesome, thanks! Much more transparent for users!

Some questions:

- Have you tried it IRL using the frontend? 
- Which [buf version](https://github.com/bufbuild/buf/releases) and ts-proto version have you autogenerated the code with? 
  - I'm using buf 1.9.0 and ts-proto 1.131.0
  - You might need to update your buf binary and/or run `yarn install` in your local `dashboard` folder to get the latest version.
-  You may need to run `yarn prettier` in the `dashboard` project. Currently, this PR has plenty of unwanted changes and I believe this could be the reason.

 If you don't want to deal with the autogenerated code, please let me know, and I can push some commits to your branch to fix it.

**Comment by dlaloue-vmware** [comment]
>     * Have you tried it IRL using the frontend?

yes. i tried again today and all was working fine.

>     * Which [buf version](https://github.com/bufbuild/buf/releases) and ts-proto version have you autogenerated the code with?
>       * I'm using buf 1.9.0 and ts-proto 1.131.0

i used the same buf version i used in other PR. it seems that i have buf 1.5.0

>     * You may need to run `yarn prettier` in the `dashboard` project. Currently, this PR has plenty of unwanted changes and I believe this could be the reason.

yes, i did run yarn prettier to not commit files that were not really touched

>       * You might need to update your buf binary and/or run `yarn install` in your local `dashboard` folder to get the latest version.

so i did that. I upgraded my buf to 1.9.0 to match your version, regenerated the code, ran yarn install/prettier.
this reduced the number of changed files by 15.

but now the frontend end-2-end tests are failing on CI. I will look to see why this is happening.

**Comment by dlaloue-vmware** [comment]
closing this PR due to the commit signing issues. Another PR has been created with proper commit signing

**Pull request closed without merging**
