### PR TITLE
Use correct config for additional clusters

### PR DESCRIPTION
**Pull request by XenoAura**
Fix: https://github.com/vmware-tanzu/kubeapps/issues/5033

### Description of the change

`clientsetForConfig` uses incorrect cluster config variable 

https://github.com/vmware-tanzu/kubeapps/blob/11c87926d6cd798af72875d01437d15ae8d85b9a/pkg/kube/kube_handler.go#L333-L336

### Benefits

Correct behavior for getting a list of namespaces for additional clusters

### Applicable issues

- fixes https://github.com/vmware-tanzu/kubeapps/issues/5033

### CODE REVIEW

**Comment by antgamdia** [comment]
Thanks for the contribution @XenoAura ! LGTM, however, could you add a unit test so that we can avoid future regressions (we are planning to deprecate Kubeops and move the logic to the kubeapps-apis service) ? 

Additionally, it seems the CircleCI checks are not passing (I mean, not failing, just that, sometimes, they don't get reported back, perhaps you need an empty commit or just merging `main` into your branch)

**Review by antgamdia — APPROVED** [review]
Forgot to actually +1 the changes 😅 , just waiting for the test to merge it.

**Comment by antgamdia** [comment]
Let me update the branch with the latest changes (mainly to trigger the CI checks, which were somehow stuck). Also, the CLA bot complained about the signing process, please let us know if you are facing any issues with it. Feel free to reach out to us in [Slack](https://kubernetes.slack.com/messages/kubeapps).

**Comment by antgamdia** [comment]
@XenoAura , is there anything I can help you with the CLA issues the bot is reporting? Or maybe with the unit test?

**Comment by castelblanque** [comment]
After removal of kubeops (#5253), parts of the enclosing code used by this PR have been migrated and thus can not be applied.
Changes have been reworked in #5286.
Thanks to @XenoAura for the contribution and creating the issue #5033.

**Pull request closed without merging**
