### PR TITLE
fix fluxcd catalog

### PR DESCRIPTION
**Pull request by kvaps**
### Description of the change

Fluxcd's HelmRepository `v1beta2` has no `status.artifact.checksum` field

### Applicable issues

fixes https://github.com/vmware-tanzu/kubeapps/issues/6863
regression introduced by  https://github.com/vmware-tanzu/kubeapps/issues/4506

### CODE REVIEW

**Comment by absoludity** [comment]
Thanks @kvaps for jumping in and looking for a solution!

> ### Description of the change
> 
> Fluxcd's HelmRepository `v1beta2` has no `status.artifact.checksum` field

[...]

> fixes #6863 regression introduced by #4506

That's interesting! Actually, checking, I don't think it was introduced by #4506 as, at the time the v1beta2 API was released, it was still using `checksum`, as you can see in the related [Flux source controller v0.22.0 docs](https://github.com/fluxcd/source-controller/blob/v0.22.0/docs/spec/v1beta2/helmcharts.md#artifact). Even just prior to the 1.0.0 release, in the [0.36.1 release they still included the `checksum` field, but had also introduced `Digest`](https://github.com/fluxcd/source-controller/blob/v0.36.1/docs/spec/v1beta2/helmcharts.md#artifact) by then. But yes, with the [first 1.0 release candidate `checksum` has been removed](https://github.com/fluxcd/source-controller/blob/v1.0.0-rc.1/docs/spec/v1beta2/helmcharts.md#artifact).

Now in our CI, it's clear that we haven't been able to prioritise work on the fluxcd support for some time, with the [version being used in CI still at v0.37.0](https://github.com/vmware-tanzu/kubeapps/blob/main/script/e2e-test.sh#L36) (of fluxcd, not source-controller) and [that release still uses v0.32.1 of source-controller](https://github.com/fluxcd/flux2/releases/tag/v0.37.0), well before the `checksum` field was removed which is why the code still works in CI. And in fact, from the [v0.32.1 docs it is before the `digest` field was added](https://github.com/fluxcd/source-controller/blob/v0.32.1/docs/spec/v1beta2/helmcharts.md#artifact).

I say all that only to show why it might require a little more work than just changing the lines over to use `digest` that you've done here (which won't pass CI with the version of fluxcd used in our integration tests). If you are keen to have a go, great! but no pressure, otherwise we'll take a look as it gets prioritised. My guess is that the following will need doing in this PR as well:

At a minimum:
- Update the [`FLUX_VERSION` used in the CI tests](https://github.com/vmware-tanzu/kubeapps/blob/main/script/e2e-test.sh#L36) to a recent version so that `digest` is present.

We can then let your PR here run against the CI tests. It could be that it passes as is, but more likely:
- there are likely to be CI/integration tests which also make the same assumption (though I can't see any from a quick grep - so we could be lucky)
- there could be other changes introduced in the newer fluxcd version which may break assumptions in the existing Kubeapps/fluxcd integration (but again, we could be lucky).

So for now, if you can update [`FLUX_VERSION`](https://github.com/vmware-tanzu/kubeapps/blob/main/script/e2e-test.sh#L36) to the latest stable fluxcd, and we can then run our integration/CI tests with your change and see. No pressure to fix it if there's a lot of fall-out, but great if you're keen :)

Cheers

**Comment by kvaps** [comment]
@absoludity thank you for feedback PR rebased

**Comment by absoludity** [comment]
Thanks @kvaps . I'll run CI with those changes, but I see you had to (?) update the k8s libraries, which unfortunately won't work yet, I don't think (we'd been holding off the k8s client-go (and friends) 0.26->0.28 upgrade because it needs some manual work. So we may need to pause this PR until that work is done. Let's see when I run.

**Comment by kvaps** [comment]
Yup, because:

```
go: github.com/fluxcd/pkg/oci@upgrade (v0.33.0) requires k8s.io/api@v0.28.4, not k8s.io/api@v0.26.7
```

**Comment by antgamdia** [comment]
I've been putting together some upgrades (mainly for triggering CI and checking it effectively works) at https://github.com/vmware-tanzu/kubeapps/pull/7219. I'd like to upgrade the CI first and perform a IRL check everything works as expected first. Let's see if after holidays we can finally merge it and get flux our flux plugin up to date again.

**Comment by antgamdia** [comment]
Hi @kvaps, thank you for reporting the issue and sending the fix. As it turned out to be a more complex change, involving several deps, CI changes, etc. I ended up addressing everything together at https://github.com/vmware-tanzu/kubeapps/pull/7219.
 
There's still some pending work (like migrating to `CertSecretRef` for future releases), but the issue you reported should be now fully addressed.

Let me close the PR, but please feel free to contribute again. Thanks again!

**Pull request closed without merging**
