### PR TITLE
[Minor]Fix log trace message to have correct values for cluster and namespace

### LINKED ISSUE #4942: [Minor]Log Message are not pointing to correct values
**Describe the bug**
the log trace message in `server_ctrl_package.go` is misleading.
[https://github.com/vmware-tanzu/kubeapps/blob/8842964b43e652d6e525d03f7e3745b414215b36/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go#L813](https://github.com/vmware-tanzu/kubeapps/blob/8842964b43e652d6e525d03f7e3745b414215b36/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go#L813)

**Expected behavior**
Cluster and namespace placeholder should be replaced

**Additional context**

### PR DESCRIPTION
**Pull request by akankshakumari393**
Signed-off-by: Akanksha Kumari [akankshakumari393@gmail.com](mailto:akankshakumari393@gmail.com)

### Correct log trace message to have correct values for cluster and namespace

This would fix the error message in `kubeapps-apis` service

### Benefits

This would give us the proper log message

### Possible drawbacks

NA

### Applicable issues

- fixes #4942

### Additional information

NA

### CODE REVIEW

**Comment by castelblanque** [comment]
Many thanks for catching and fixing this issue @akankshakumari393!!!
Really appreciated 😃

**Review by castelblanque — APPROVED** [review]

**Comment by akankshakumari393** [comment]
Thanks for the quick response @castelblanque. When can we get this merged?

**Comment by castelblanque** [comment]
> When can we get this merged?

Now that the CLA is signed, we can mege it straight away. Thanks!

**Comment by ppbaena** [comment]
Thanks for your contribution @akankshakumari393! Remeber you can follow the [#Kubeapps channel](https://kubernetes.slack.com/archives/C9D3TSUG4) on the Kubernetes Slack server to keep you posted on new releases, updates and news about Kubeapps.

**Pull request merged**
