### PR TITLE
Use structured logs in kubeapp-apis service

### LINKED ISSUE #4193: Use structured logs  (`log.InfoS(...)`)
As per the discussion in https://github.com/kubeapps/kubeapps/pull/4180#discussion_r793990507
and https://github.com/kubeapps/kubeapps/issues/3848#issuecomment-1019959653, it would be nice if we moved to structured logs ([more info here](https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/)).

Specifically, it means:

- [ ] Use `log.InfoS(...)` in our log traces.
- [ ] Add a ` --logging-format` to our deployments to let users customize the format; for instance, using json-

### PR DESCRIPTION
**Pull request by akankshakumari393**
### Description of the change

This PR uses structured logs wherever possible. The changes are scoped to `kubeapp-apis` service and dependent package.

### Benefits

Using structured logs would make automated parsing of the logs easy

### Possible drawbacks
NA

### Applicable issues

- fixes #4193

### CODE REVIEW

**Review by antgamdia — APPROVED** [review]
Awesome, thanks for the effort! LGTM
However, I've carried out a quick search of `log.Infof(`,  `log.Info(`, `log.Errorf` and there are still some matches in the source code. Do you have intentions to also update them?

Besides, we also have `log.Warning(`, `log.Warningf(`, but according to klog (_ErrorS structured logs to the ERROR, WARNING, and INFO logs._), it seems that the warnings are also logged using the `ErrorS`.

Happy to accept and land this PR or leave it open if you want to send more changes and move every log trace to the structured format. 

Again, thanks for the effort :)

**Comment by akankshakumari393** [comment]
Hey @antgamdia I agree that there are still some references of `log.Infof(`, `log.Info(`, `log.Errorf` but they are using custom formatting. So was not sure If we should make changes in that. I think we should get this PR merged. Meanwhile I will raise a seperate PR for leftover matches in a 2nd PR for `kubeapps-apis` service. Then we would move to other packages.

**Comment by antgamdia** [comment]
> . I think we should get this PR merged. Meanwhile I will raise a seperate PR for leftover matches in a 2nd PR for `kubeapps-apis` service.

Great! Will do that way then. After the v2.4.6 release we have started merging pending PRs we had, so some conflicts have emerged. However, I've just solved them and as soon as the CI check go green, I'll merge the PR :)

**Comment by akankshakumari393** [comment]
Cool, Thanks for quick response.

**Comment by gfichtenholt** [comment]
Please finish this work. In the the current state it is difficult to read the server log because of inconsistent formatting of the messages, e.g.:
```
I0719 06:22:34.003030       1 watcher_cache.go:563] -syncHandler(helmrepositories:default:my-podinfo-3z9x)
I0719 06:22:34.003071       1 watcher_cache.go:301] -processNextWorkItem()
I0719 06:22:34.003085       1 watcher_cache.go:256] +processNextWorkItem()
I0719 06:22:34.014161       1 watcher_cache.go:649] "+fetchForOne" key="helmrepositories:default:my-podinfo-3z9x"
```

**Pull request merged**
