### PR TITLE
[Bug] Parse the yaml before dumping it back to string

### LINKED ISSUE #5894: [Bug] Installation values formatted incorrectly
**Describe the bug**
The installation values  are not properly formatted in the yaml format in the installation values section

**To Reproduce**

1. Go to Kubeapps UI and open the details page of any release
3. Scroll down to Installation Values

**Expected behavior**
The installation values should be properly formatted in yaml format

**Screenshots**
Before
Before

Created a PR for resolution #5893 

After
After

**Desktop (please complete the following information):**

- Version 2.6.2
- Kubernetes version 1.24.3
- Package version default in kubeapps helm chart

**Additional context**

### PR DESCRIPTION
**Pull request by mittalvaibhav1**
Signed-off-by: Vaibhav Mittal <53215737+mittalvaibhav1@users.noreply.github.com>

### Description of the change
Fix the incorrect formatting of the installation values on the Kubeapps UI

### Benefits
- Cleaner UI 😀 

### Possible drawbacks
- None as far as ik

### Applicable issues

- fixes #5894

### CODE REVIEW

**Review by absoludity — APPROVED** [review]
As long as CI is happy, +1... thanks again for jumping in with the report and fix.

**Comment by mittalvaibhav1** [comment]
Good to go :)

**Comment by absoludity** [comment]
Woo!

**Comment by absoludity** [comment]
Just want to double-check: @antgamdia : I'm assuming there wasn't a reason you didn't use `parseToJS` here was there? (I'm 99% sure you would have left a comment if that were the case, so it's probably just something that was missed, but want to be sure).

**Comment by antgamdia** [comment]
> if that were the case, so it's probably just something that was missed, but want to be sure).

From memory, I can't recall why I didn't use it; I mean, when performing IRL tests we should have noticed it, but we didn't. So, either I actually missed it (most likely, I guess 😆 ) or the latest changes on the custom values have had a sort of side effect here.
Anyway, let's keep an eye on the whole process of displaying/editing values just in case.

**Pull request merged**
