### PR TITLE
6891 - Add _blank attribute to links on LinkRenderer to open urls on …

### LINKED ISSUE #6891: Open links of "installation notes" in new tab
**Background and rationale**
The developer of a helm chart, usually puts the link to access to the deployed application in the `Notes.txt`, which is read as markdown and rendered in the "Installation notes" panel of the application details web page of kubeapps. That link or any other in this notes usually goes to another web page and, in my opinion, should be openned in a new browser tab or window.

**Description**
Open links of "Installation notes" as external, usually in a new tab, but it is up to the browser configuration, just adding the property `target="_blank"` to the <a> tag is enough.

**Acceptance criteria**
If you think this is not the desirable default behaviour, I suggest to add some option to enable this mode.

**Additional context**
I tried directly writing the html code like:
```
<a href="" target="_blank">link</a>
```
And is well rendered as a link, but the property `target` disappears.

### PR DESCRIPTION
**Pull request by vash-knives**
### Description of the change

Fixes the #6891 ticket

### Benefits

Opens a new tab for external links

### Possible drawbacks
N/A

### Applicable issues

- fixes #6891 

### Additional information
N/A

### CODE REVIEW

**Review by absoludity — APPROVED** [review]
So every non-internal link for the dashboard-rendered markdown (Readme's, Notes) will be opened in a new tab - makes sense.

Thanks @vash-knives . Once the contributor agreement is approved, I'll land it.

**Comment by vash-knives** [comment]
@absoludity that is correct. i figured a user would prefer to be on the same tab if it's external. it does seem like on that "Notes.txt" it's mostly external links since it's for the chart's instructions anyway. I can update code if  the internal should be on a new tab as well. 

Also, anything I need to do for that contributor agreement goes through? I'm new to this so still trying to figure that out.

**Comment by absoludity** [comment]
> @absoludity that is correct. i figured a user would prefer to be on the same tab if it's external. it does seem like on that "Notes.txt" it's mostly external links since it's for the chart's instructions anyway. I can update code if the internal should be on a new tab as well.

I think it's best as is (as internal links are internal to the page, not just the site), thanks :)

> 
> Also, anything I need to do for that contributor agreement goes through? I'm new to this so still trying to figure that out.

Nothing to do but wait at the moment, I assume it's waiting for someone to check a box which will automatically leave a comment here (as mentioned in the auto comment above), then we can land your change.

**Comment by vash-knives** [comment]
ah finally! @antgamdia , lmk if there's anything else i need to do.

**Comment by absoludity** [comment]
> ah finally! @absoludity , lmk if there's anything else i need to do.

Excellent, but yeah, if you can, could you sign the commit? See https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits (you might need to uncommit, then sign the commit as per the link, then force push).

If you've had enough, no problem - I can land it as is since it's such a small change. Just let me know.

**Comment by vash-knives** [comment]
> Excellent, but yeah, if you can, could you sign the commit? See https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits (you might need to uncommit, then sign the commit as per the link, then force push).

@absoludity So I got the gpg set up (eventually), see if that worked?  I am not 100% I did it correctly. This is my first time signing using gpg, I appreciate your patience. Let me know if it did not work.

**Comment by absoludity** [comment]
> @absoludity So I got the gpg set up (eventually), see if that worked? I am not 100% I did it correctly. This is my first time signing using gpg, I appreciate your patience. Let me know if it did not work.

Great, yes - that worked. You can see by looking at the commit https://github.com/vmware-tanzu/kubeapps/pull/6903/commits and seeing the "Verified" (if you click on it, it tells you its' verified by your gpg key). I'll re-run the workflow.

**Review by absoludity — APPROVED** [review]

**Comment by vash-knives** [comment]
@absoludity nice, glad that worked!

**Pull request merged**
